### PR TITLE
Create typescript definitions

### LINKED ISSUE #2: Create typescript definitions
Hi @diachedelic,

Thanks for implementing the iOS part for background geolocation that was missing in the original package that you forked. I tested it on both platforms and it seems to be working great so far. The latest distanceFilter addition should help with a battery drainage. It seems a lot better and simpler than other alternatives.

It would be great if the project contained typescript definitions. I'm sure it would be helpful to many people. Could you take a look at that? The original package had that covered here: https://github.com/seididieci/capacitor-backround-geolocation/search?l=typescript

Cheers,
Patrik

### PR DESCRIPTION
**Pull request by pdrhlik**
This PR creates typescript definitions and adds simple documentation to each function and property. It also modifies a README a bit to reflect the changes, though not extensively yet.

The naming conventions were inspired by https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API so it stays as close as possible.

Closes #2

### CODE REVIEW

**Comment by pdrhlik** [comment]
The only thing that is not typed now is the Geolocation error. What is the structure of that error, @diachedelic? Does it return anything else than a code property with a NOT_AUTHORIZED value or not for now?

I would fix that right away, thanks.

**Comment by diachedelic** [comment]
I have some comments:

1. Why does this configure the Typescript compiler? Is this required for typings?
2. Why does it now expose an unimplemented Web plugin?
3. It is confusing to give the single object parameter a name, can it be anonymous, or just `value`? `removeWatcher(id: {id: string})`
4. Some fields on the location object are optional. Can this be part of the typescript definition?
5. The project uses JSLint for javascript, which is incompatible with Prettier. Also, I have come to dislike how Prettier formats javascript.
6. In the README, I would prefer to show the Typescript usage separately from the JS usage. This is because everyone uses JS, but not everyone uses Typescript.
7. `addWatcher` does not return a Promise.

Sorry, actually I am not going to merge this. The changes introduce too much complexity and repetition. I was imagining it would simply be the addition of a single file containing type definitions.

**Comment by pdrhlik** [comment]
I followed the official instructions for creating Capacitor plugins and all this complexity seems to be necessary. I put back all the files that where missing in this repo when you create a plugin (v2) using `npx @capacitor/cli plugin:generate`.

1. It's probably not required but I would call it good practice. It checks and validates the definitions for you. It's only a devDependency.
2. I had some issues making it work without it. I would add a simple web implementation in the future.
3. When I only passed a `value` to `addWatcher()`, it didn't work. Is it possible that it's because of this line? `String callbackId = call.getString("id");` in [BackgroundGeolocation.java#L158](https://github.com/capacitor-community/background-geolocation/blob/7ff19e69de96817aa21268ae8a9913dbd0554938/android/src/main/java/com/equimaps/capacitor_background_geolocation/BackgroundGeolocation.java#L158)?
4. Optional fields are not a problem at all. It seems that only `latitude`, `longitude` and `time` are always present. Is that right?
5. Again, I used the official boilerplate. I think prettier doesn't have to be a part of this.
6. This makes sense.
7. That will be easy to fix.

I hope you will reconsider because every official and non-official @capacitor-community plugin have typescript definitions and they do it exactly like this.

I think that this plugin has a great potential and I would like to help make it better. Otherwise I'll just tend to my forked version.

**Comment by diachedelic** [comment]
Thanks for your work on this. I have slightly modified the definitions you wrote and release them in v0.3.7, please let me know if they are not satisfactory.

**Pull request closed without merging**
