### PR TITLE
Reduce the need for some android settings

### PR DESCRIPTION
**Pull request by HarelM**
Related to the discussion in #73 - this PR will automatically add the Manifest.xml parts related to Android build.
I've added it to the manifest and removed it from the readme.
I've took the inspiration from:
https://github.com/ionic-team/capacitor-plugins/blob/d97898662d0ba037e5f8448990a91de5ec6a4234/local-notifications/android/src/main/AndroidManifest.xml

I'm not sure where to put the part saying this should be removed from the Manifest.xml in case you upgrade from a previous version though...

Any thought are welcome!
Thanks for all the work around this plugin!
I've took it from some test run with my phone and app and it seems to run very well in the background :-)

### CODE REVIEW

**Comment by diachedelic** [comment]
That's promising. Could you update the example's manifest and give it a test please?

**Comment by HarelM** [comment]
Done. working as expected as far as I can see :-)

**Comment by diachedelic** [comment]
Great, please squash your commits and I will merge.

**Comment by HarelM** [comment]
You can squash-merge them here, can't you?

**Comment by HarelM** [comment]
Thanks! Let me know when a new version is available. :-)

**Pull request merged**
